# Generated by Django 6.1 on 2026-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_regionaloffice_companyinfo_facebook_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyinfo",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text='Digits only, with country code, no "+" or spaces, e.g. "994501234567". Leave blank to hide the WhatsApp button.',
                max_length=20,
            ),
        ),
    ]
