# Generated by Django 6.1 on 2026-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short description shown on the partner card."
            ),
        ),
    ]
