# Generated by Django 6.1 on 2026-08-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegionalOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("region_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "region_name"],
            },
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="hero_heading",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="hero_image",
            field=models.ImageField(blank=True, null=True, upload_to="hero/"),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="hero_subheading",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="companyinfo",
            name="linkedin_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="companyinfo",
            name="google_map_embed_url",
            field=models.URLField(
                help_text='The src URL from Google Maps "Embed a map" iframe, shown on the contact page.',
                verbose_name="Google Maps embed URL",
            ),
        ),
    ]
