# Generated by Django 6.1 on 2026-08-20 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="certification_note",
            field=models.CharField(
                blank=True,
                help_text='e.g. "Certified for European and North American Markets."',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dosage_usage",
            field=models.TextField(blank=True, help_text="Application rate / usage instructions."),
        ),
        migrations.AddField(
            model_name="product",
            name="formulation",
            field=models.CharField(
                choices=[
                    ("sc", "Suspension Concentrate"),
                    ("ec", "Emulsifiable Concentrate"),
                    ("wp", "Wettable Powder"),
                    ("gr", "Granule"),
                    ("sl", "Soluble Liquid"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_bio_rational",
            field=models.BooleanField(
                default=False, help_text='Shows a "Bio-Rational" badge on the catalogue card.'
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="purity_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='e.g. 99.8 for "99.8% Pure".',
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="registration_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="sds_file",
            field=models.FileField(
                blank=True,
                help_text="Safety Data Sheet PDF.",
                null=True,
                upload_to="sds/",
                verbose_name="SDS document",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="subtitle",
            field=models.CharField(
                blank=True, help_text='Short tagline, e.g. "Advanced Fungicide".', max_length=200
            ),
        ),
        migrations.CreateModel(
            name="ChemicalComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "amount",
                    models.CharField(help_text='e.g. "500 g/kg (50% w/w)".', max_length=100),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chemical_components",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.ImageField(upload_to="products/gallery/")),
                ("alt_text", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_images",
                        to="catalogue.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
