# Generated by Django 6.1 on 2026-08-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0003_remove_product_category_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name_az",
            field=models.CharField(blank=True, max_length=200, verbose_name="Name (Azerbaijani)"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(blank=True, max_length=200, verbose_name="Name (English)"),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(blank=True, max_length=200, verbose_name="Name (Russian)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="Canonical name, used for the slug and admin.", max_length=200
            ),
        ),
    ]
