# Generated by Django 6.1 on 2026-08-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0004_product_name_az_product_name_en_product_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Shown on the homepage category strip. Use a simple, mostly-transparent icon (like the site's other icon-*.svg assets) — it's recolored white over an automatically colored badge, so a busy or full-color image won't read well.",
                null=True,
                upload_to="categories/",
            ),
        ),
    ]
